### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by TaylanTatli** [satanas/Turpial#289] opened 2014-03-07 23:22 UTC
When i try to add my twitter acount, there is only blank page.

![dosqqyx](https://f.cloud.github.com/assets/754514/2363531/42c432c8-a64f-11e3-8496-4a7e139714b0.png)

**Comment by dpshelio** [comment] 2014-03-09 10:31
@DoubleT34 I've reported the [same issue in the turpial repository](https://github.com/Turpial/Turpial/issues/78).  I haven't managed to make it work.

I'm using Archlinux, and I'm behind a proxy.  I've tried too by copying the `~/.turpial` folder from a different machine (with fedora) where it works (without proxy though).

**Comment by TaylanTatli** [comment] 2014-03-09 11:51
It's weird. There was a dns problem, so lots of apps gives me host problem but i solved this issue by disabling ipv6 on kernel. Now everything works except turpial. Using corebird right now without problem.

**Comment by satanas** [comment] 2014-03-09 14:37
Are you both behind a proxy? If so try to set the proxy information in Turpial' settings.

@DoubleT34 What happen if you try to run the examples on the [quickstart guide](https://github.com/satanas/libturpial/blob/development/docs/quickstart.rst)?

**Comment by dpshelio** [comment] 2014-03-09 14:42
@satanas I have configured the proxy in the settings, in multiple different ways (through the turpial interface and on the Turpial's config file).  I don't think the problem is there.  As I mentioned in the other repository, I managed to get a pin using the libturpial, but I cannot then use it in Turpial because it's a new instance (so a new pin).

**Comment by TaylanTatli** [comment] 2014-03-10 20:36
No. I don't use any proxy. BTW, i don't understand this quickstart. English is not my main language. libturpial is just an library how can use commands on this guide?

**Comment by TaylanTatli** [comment] 2014-03-10 20:42
┌─[✗]─[doublet@chakra]─[~]
└──> python2
Python 2.7.6 (default, Feb  9 2014, 21:54:41) 
[GCC 4.8.1 20130725 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from libturpial.api.models.account import Account
> > > 
> > > account = Account.new('twitter')
> > > 
> > > url = account.request_oauth_access()
> > > from libturpial.api.models.account import Account
> > > account = Account.new('twitter')
> > > url = account.request_oauth_access()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/site-packages/libturpial/api/models/account.py", line 162, in request_oauth_access
> > >     return self.protocol.request_token()
> > >   File "/usr/lib/python2.7/site-packages/libturpial/lib/protocols/twitter/twitter.py", line 93, in request_token
> > >     return self.http.request_token()
> > >   File "/usr/lib/python2.7/site-packages/libturpial/lib/http.py", line 311, in request_token
> > >     req = requests.get(self.request_token_url, headers=oauth_request.to_header())
> > >   File "/usr/lib/python2.7/site-packages/requests/api.py", line 55, in get
> > >     return request('get', url, *_kwargs)
> > >   File "/usr/lib/python2.7/site-packages/requests/api.py", line 44, in request
> > >     return session.request(method=method, url=url, *_kwargs)
> > >   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 361, in request
> > >     resp = self.send(prep, *_send_kwargs)
> > >   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in send
> > >     r = adapter.send(request, *_kwargs)
> > >   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 356, in send
> > >     raise ConnectionError(e)
> > > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /oauth/request_token (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)
> > > url = account.request_oauth_access()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.7/site-packages/libturpial/api/models/account.py", line 162, in request_oauth_access
> > >     return self.protocol.request_token()
> > >   File "/usr/lib/python2.7/site-packages/libturpial/lib/protocols/twitter/twitter.py", line 93, in request_token
> > >     return self.http.request_token()
> > >   File "/usr/lib/python2.7/site-packages/libturpial/lib/http.py", line 311, in request_token
> > >     req = requests.get(self.request_token_url, headers=oauth_request.to_header())
> > >   File "/usr/lib/python2.7/site-packages/requests/api.py", line 55, in get
> > >     return request('get', url, *_kwargs)
> > >   File "/usr/lib/python2.7/site-packages/requests/api.py", line 44, in request
> > >     return session.request(method=method, url=url, *_kwargs)
> > >   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 361, in request
> > >     resp = self.send(prep, *_send_kwargs)
> > >   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in send
> > >     r = adapter.send(request, *_kwargs)
> > >   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 356, in send
> > >     raise ConnectionError(e)
> > > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /oauth/request_token (Caused by <class 'socket.gaierror'>: [Errno -5] No address associated with hostname)
> > > from libturpial.api.models.account import Account
> > > account = Account.new('twitter')
> > > from libturpial.api.models.account import Account

Nothing. :/

**Comment by satanas** [comment] 2014-03-10 22:16
Great! Thanks for that test. I can see clearly that the problem is with
DNS. For some reason your DNS is not resolving api.twitter.com

**Comment by TaylanTatli** [comment] 2014-03-11 10:05
But how? I'm using google dns and i can access twitter.com

**Comment by TaylanTatli** [comment] 2014-03-11 22:33
BTW, i tried turpial on xubuntu 12.04.4 and it was working but turpial for precise is old version and then i tried turpial on 13.10 and it was not working, same blank page. 12.04 is working 13.10 is not working.

**Comment by satanas** [comment] 2014-03-18 17:54
Yep, you could be using google DNS but still have no access to HTTPS protocol. Can you try this:
`ping api.twitter.com`

and this:
`curl -k https://api.twitter.com`

First one will let us know if your DNS is resolving the host and second will tell us if your connection can go through SSL.

**Comment by dpshelio** [comment] 2014-03-20 09:20
@satanas my problem is not related with that either.

``` shell
me@mymachine ~ % ping api.twitter.com 
PING api.twitter.com (199.16.156.104) 56(84) bytes of data.
64 bytes from 199.16.156.104: icmp_seq=1 ttl=52 time=340 ms
64 bytes from 199.16.156.104: icmp_seq=2 ttl=52 time=340 ms
64 bytes from 199.16.156.104: icmp_seq=3 ttl=52 time=340 ms
--- api.twitter.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 340.828/340.889/340.925/0.675 ms
```

and 

``` shell
me@mymachine ~ % curl -k https://api.twitter.com
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
 ...
  </head>
  <body>
        ...
                <a class="nav-logo-link" href="//twitter.com">
                  <span class="Icon Icon--bird"><span class="visuallyhidden">Twitter</span></span>
       ...  
            <li class="first">&copy; 2014 Twitter</li>
            <li><a href="https://twitter.com/about">About</a></li>
            <li><a href="https://support.twitter.com">Help</a></li>
            <li><a href="http://status.twitter.com/">Status</a></li>
    <script src="https://abs.twimg.com/errors/404-edf30e3e35a76d0e7755c4a48e17199d.js"></script>
  </body>
</html>
```

If I run the guide, as you suggested above:

``` python
from libturpial.api.models.account import Account
account = Account.new('twitter')
url = account.request_oauth_access()
print url
```

copy the access code:

``` python
account.authorize_oauth_access('********')
```

I get a

``` python
error: [Errno 111] Connection refused
```

because I've not set the proxy.  But though I've found that there's an mplementation to parse the proxy](http://libturpial.readthedocs.org/en/latest/search.html?q=proxy&check_keywords=yes&area=default), I've been not able at all to find how to do so.

Also, since the @Turpial account does not have the repository anymore, this is the warning message that I get when opening Turpial:

``` error
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
```

**Comment by TaylanTatli** [comment] 2014-03-20 16:29
[doublet@chakra ~]$ ping api.twitter.com
PING api.twitter.com (199.16.156.40) 56(84) bytes of data.
64 bytes from 199.16.156.40: icmp_seq=1 ttl=235 time=182 ms
64 bytes from 199.16.156.40: icmp_seq=2 ttl=235 time=200 ms
64 bytes from 199.16.156.40: icmp_seq=3 ttl=235 time=183 ms
64 bytes from 199.16.156.40: icmp_seq=4 ttl=235 time=188 ms

--- api.twitter.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 30595ms
rtt min/avg/max/mdev = 182.711/188.726/200.154/6.889 ms
[doublet@chakra ~]$ curl -k https://api.twitter.com
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Language" content="en-us">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Twitter / ?</title>
    <link href="//abs.twimg.com/favicons/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link rel="stylesheet" href="//abs.twimg.com/errors/fullscreen_errors.css">
  </head>
  <body>
    <div class="topbar js-topbar">
      <div class="global-nav" data-section-term="top_nav">
        <div class="global-nav-inner">
          <div class="container">
            <ul class="nav js-global-actions">
              <li class="home">
                <a class="nav-logo-link" href="//twitter.com">
                  <span class="Icon Icon--bird"><span class="visuallyhidden">Twitter</span></span>
                </a>
              </li>
            </ul>
            <div class="pull-right">
              <ul class="nav secondary-nav">
                <li><a href="//twitter.com" id="homeLink">Home &rarr;</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="blue-sky">
      <div class="body-content">

```
      <h1>Sorry, that page doesn’t exist!</h1>
      <p>Thanks for noticing&mdash;we're going to fix it up and have things back to normal soon.</p>
      <form class="search-404" action="https://twitter.com/search" method="get">
        <input id="search_q" name="q" type="text" aria-label="Search query" placeholder="Search for a topic, full name, or @username">
        <input class="btn" id="search_submit" type="submit" value="Search">
      </form>

    <div class="footer">
      <ul class="languages">

          <li><a data-language="af" href="#">Afrikaans</a></li>

          <li><a data-language="ar" href="#">العربية</a></li>

          <li><a data-language="be" href="#">беларуская</a></li>

          <li><a data-language="bg" href="#">Български език</a></li>

          <li><a data-language="ca" href="#">català</a></li>

          <li><a data-language="cs" href="#">Čeština</a></li>

          <li><a data-language="cy" href="#">Cymraeg</a></li>

          <li><a data-language="da" href="#">Dansk</a></li>

          <li><a data-language="de" href="#">Deutsch</a></li>

          <li><a data-language="el" href="#">Ελληνικά</a></li>

          <li><a data-language="en" href="#">English</a></li>

          <li><a data-language="en-gb" href="#">English (UK)</a></li>

          <li><a data-language="es" href="#">Español</a></li>

          <li><a data-language="eu" href="#">Euskara</a></li>

          <li><a data-language="fa" href="#">فارسی</a></li>

          <li><a data-language="fi" href="#">Suomi</a></li>

          <li><a data-language="fil" href="#">Filipino</a></li>

          <li><a data-language="fr" href="#">Français</a></li>

          <li><a data-language="ga" href="#">Gaeilge</a></li>

          <li><a data-language="gl" href="#">Galego</a></li>

          <li><a data-language="he" href="#">עברית</a></li>

          <li><a data-language="hi" href="#">हिन्दी</a></li>

          <li><a data-language="hr" href="#">hrvatski</a></li>

          <li><a data-language="hu" href="#">Magyar</a></li>

          <li><a data-language="id" href="#">Indonesian</a></li>

          <li><a data-language="it" href="#">Italiano</a></li>

          <li><a data-language="ja" href="#">日本語</a></li>

          <li><a data-language="ko" href="#">한국어</a></li>

          <li><a data-language="ku" href="#">Kurdî (Kurmanji)</a></li>

          <li><a data-language="msa" href="#">Malay</a></li>

          <li><a data-language="nl" href="#">Nederlands</a></li>

          <li><a data-language="no" href="#">Norsk</a></li>

          <li><a data-language="pl" href="#">Polski</a></li>

          <li><a data-language="pt" href="#">português (Brasil)</a></li>

          <li><a data-language="ro" href="#">română</a></li>

          <li><a data-language="ru" href="#">Русский</a></li>

          <li><a data-language="sk" href="#">slovenčina</a></li>

          <li><a data-language="sq" href="#">shqip</a></li>

          <li><a data-language="sr" href="#">srpski</a></li>

          <li><a data-language="sv" href="#">Svenska</a></li>

          <li><a data-language="th" href="#">ภาษาไทย</a></li>

          <li><a data-language="tr" href="#">Türkçe</a></li>

          <li><a data-language="uk" href="#">Українська мова</a></li>

          <li><a data-language="ur" href="#">اردو</a></li>

          <li><a data-language="vi" href="#">Tiếng Việt</a></li>

          <li><a data-language="xx-lc" href="#">LOLCATZ</a></li>

          <li><a data-language="zh-cn" href="#">简体中文</a></li>

          <li><a data-language="zh-tw" href="#">繁體中文</a></li>

      </ul>
      <ul class="links">
        <li class="first">&copy; 2014 Twitter</li>
        <li><a href="https://twitter.com/about">About</a></li>
        <li><a href="https://support.twitter.com">Help</a></li>
        <li><a href="http://status.twitter.com/">Status</a></li>
      </ul>
    </div>
  </div>
</div>
<script src="https://abs.twimg.com/errors/404-edf30e3e35a76d0e7755c4a48e17199d.js"></script>
```

  </body>
</html>
[doublet@chakra ~]$

**Comment by milmazz** [comment] 2014-03-20 16:50
@dpshelio Since libturpial depends on [requests](http://docs.python-requests.org/en/latest/) you can also configure proxies by
setting the environment variables `HTTP_PROXY` and `HTTPS_PROXY`.

Can you try this at the command line?

```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

Please adjust the values according to your configuration, then:

``` python
$ python
>>> from libturpial.api.models.account import Account
>>> account = Account.new("twitter")
>>> url = account.request_oauth_access()
>>> print url
>>> account.authorize_oauth_access('******')
>>> 
```

If everything it's OK proceed to register your account as described in the [Quickstart](http://libturpial.readthedocs.org/en/latest/quickstart.html) guide

**Update:** Before start please remove your `~/.turpial` folder (the one that you copied from Fedora), who knows.

**Closed as completed** 2014-06-07 15:08 UTC
Labels: limbo
